[#repositories]
== Network repositories

It is quite common to use network repositories when we performed automated installations.

Although there are several ways to make repositories available through the network we are going to use http/https for that purpose.

First we have to install an http server in a machine to make repositories available:

[source,bash,subs="+macros,+attributes"]
[root@httpd ~]# dnf install httpd -y
...
[root@httpd ~]# systemctl enable --now httpd

By default the http content will be stored at **/var/www/html** directory so we will create a directory there to store the repositories and a directory named **ks** to store the kickstart files:

[source,bash,subs="+macros,+attributes"]
[root@httpd ~]# mkdir /var/www/html/{repo,ks}

In the **/var/www/html/repo/** directory create one directory per repository and copy the RPM files.

TIP: You can copy the **BaseOS** and **AppStream** repositories for the RHEL install DVD for instance.

TIP: From a RHEL system you can mirror a repository using the **reposync** command provided by the **dnf-utils** package.

TIP: You can modify or create your own repositories using the **createrepo** command provided by the **createrepo** package.

To access the repository you can use the URL **http://httpd-server/repo/REPOSITORY-NAME**.